@startuml

class User {
  - int ID
  - String FirstName
  - String LastName
  - String Login
  - String Password
}

class Color {
  - int ID
  - int UserID
  - String Name
}

' Relationship: One user can have 0 or many colors
User "1" *-- "0 to Many" Color : owns/creates >

@enduml